export const services =  {
    categories: ['All', 'Chinese', 'North Indian', 'South Indian'],
    packages: [
        { id: 1, image: '/assets/img/Services/service-1.jpg', title: 'Idli', category: 'South Indian', description: [ {chef: 'George',cost: '$10'},{chef: 'Laura',cost: '$6'}]},
        { id: 2, image: '/assets/img/Services/service-2.jpg', title: 'Lemon Rice', category: 'South Indian', description: [ {chef: 'Sherry',cost: '$5'}]},
        { id: 3, image: '/assets/img/Services/service-3.jpg', title: 'Tandoori Roti', category: 'North Indian', description: [ {chef: 'Laura',cost: '$10'}, {chef: 'Krish',cost: '$8'}]},
        { id: 4, image: '/assets/img/Services/service-4.jpg', title: 'Butter Chicken', category: 'North Indian', description: [ {chef: 'Macy',cost: '$10'},{chef: 'Gomathy',cost: '$10'}]},
        { id: 5, image: '/assets/img/Services/service-5.jpg', title: 'Rava Idli', category: 'South Indian', description: [ {chef: 'George',cost: '$10'}]},
        { id: 6, image: '/assets/img/Services/service-6.jpg', title: 'Fenugreek Idli', category: 'South Indian', description: [ {chef: 'Susan',cost: '$5'}, {chef: 'Claire',cost: '$4'}]},
        { id: 7, image: '/assets/img/Services/service-7.jpg', title: 'Egg Salad', category: 'Chinese', description: [ {chef: 'Jan',cost: '$10'},{chef: 'Susan',cost: '$9'}] },
        { id: 8, image: '/assets/img/Services/service-8.jpg', title: 'Chicken Salad', category: 'Chinese', description: [ {chef: 'George',cost: '$10'}, {chef: 'Jan',cost: '$10'}] },
        { id: 9, image: '/assets/img/Services/service-9.jpg', title: 'Romali Roti', category: 'North Indian', description: [ {chef: 'Sherry',cost: '$2'}, {chef: 'Steph',cost: '$2'}] },
        { id: 10, image: '/assets/img/Services/service-10.jpg', title: 'Chicken Curry', category: 'South Indian', description: [ {chef: 'Harini',cost: '$10'}] },
        { id: 11, image: '/assets/img/Services/service-11.jpg', title: 'Pork and Salad', category: 'Chinese', description: [ {chef: 'George',cost: '$10'}, {chef: 'Harini',cost: '$10'}] },
        { id: 12, image: '/assets/img/Services/service-12.jpg', title: 'Pumpkin Curry', category: 'South Indian', description: [ {chef: 'Tracy',cost: '$10'}, {chef: 'Harini',cost: '$10'}] },
        { id: 13, image: '/assets/img/Services/service-13.jpg', title: 'Noodles', category: 'Chinese', description: [ {chef: 'George',cost: '$6'}] },
        { id: 14, image: '/assets/img/Services/service-14.jpg', title: 'Barley Porridge', category: 'North Indian', description: [ {chef: 'George',cost: '$9'}] },
        { id: 15, image: '/assets/img/Services/service-15.jpg', title: 'Sushi', category: 'Chinese', description: [ {chef: 'George',cost: '$10'}] },
        { id: 16, image: '/assets/img/Services/service-16.jpg', title: 'Indian Sandwich', category: 'North Indian', description: [ {chef: 'George',cost: '$11'}] },
        { id: 17, image: '/assets/img/Services/service-17.jpg', title: 'Indian Pasta', category: 'South Indian', description: [ {chef: 'George',cost: '$15'}] },
        { id: 18, image: '/assets/img/Services/service-18.jpg', title: 'Indian sliders', category: 'South Indian', description: [ {chef: 'George',cost: '$18'}] },
        { id: 19, image: '/assets/img/Services/service-19.jpg', title: 'Chicken Soup', category: 'Chinese', description: [ {chef: 'George',cost: '$20'}] },
        { id: 20, image: '/assets/img/Services/service-20.jpg', title: 'Samosi', category: 'South Indian', description: [ {chef: 'George',cost: '$15'}] },
    ],
}